# dataset constants
DATASET_FILENAME = 'test.txt'
READ_NEW_LINES = False
COLLAPSE_WHITESPACE = True
CASE_INSENSITIVE = True

# architecture constants
NUM_LAYERS = 1
NUM_LSTM_UNITS = 218
USE_MY_LSTM = False

# training constants
EPOCHS = 20
LEARNING_RATE = 0.001
CLIP_GRADIENT = 5
BATCH_SIZE = 1
STEP_SIZE = 10
PRINT_EPOCH_INFO_RATE = 100

TEST_MODEL_FILENAME = '__latest__'
LATEST_TEST_MODEL_FILENAME = '__latest__'
SAMPLE_PRIME = 'abc'
SAMPLE_LENGTH = 9
