DATASET_FILENAME = 'anna.txt'
READ_NEW_LINES = False
COLLAPSE_WHITESPACE = True

NUM_LAYERS = 2
NUM_LSTM_UNITS = 218

EPOCHS = 1
LEARNING_RATE = 0.001
CLIP_GRADIENT = 5
BATCH_SIZE = 10
STEP_SIZE = 5
PRINT_EPOCH_INFO_RATE = 10

TEST_MODEL = '__latest__'
LATEST_TEST_MODEL = '__latest__'
SAMPLE_PRIME = 'The'
SAMPLE_LENGTH = 10

# LOAD_MODEL = ''
# LOAD_LATEST = False
